
[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "opentelemetry-instrumentor-dramatiq"
version = "0.1.2"
description = "An instrumentor for dramatiq library"
readme = "README.md"
authors = [{ name = "Sunil", email = "shrest4647+pip@gmail.com" }]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = [
    "dramatiq",
    "opentelemetry",
    "instrumentation",
    "tracing",
    "telemetry",
]
dependencies = [
    "dramatiq >= 1.2",
    "opentelemetry-api >= 1.11.0",
    "opentelemetry-instrumentation >= 0.31b0",
    "opentelemetry-semantic-conventions",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["pytest", "pip-tools", "bumpver", "pika", "redis"]

[project.urls]
Homepage = "https://github.com/Shrest4647/opentelemetry-instrumentor-dramatiq"


[bumpver]
current_version = "0.1.2"
version_pattern = "MAJOR.MINOR.PATCH"

[bumpver.file_patterns]
"pyproject.toml" = [
    "^version = \"{version}\"",
    "^current_version = \"{version}\"",
]
"opentelemetry_instrumentor_dramatiq/src/version.py" = [
    "__version__ = \"{version}\"",
]
